### ISSUE TITLE
How do I do this?

### ISSUE THREAD

**Issue by sidequestboy** [Alkaid-Benetnash/EmuBTHID#2]
Hey buddy, thanks for the project. I'm trying to run this on Arch Linux, and pair to it from another Arch Linux computer, or an Android phone, but it doesn't show up as discoverable. Are there special steps besides running `main.py` as root?

**Comment by Alkaid-Benetnash** [comment]
Hi @jameh,
It has been a long time since I wrote this simple emulator. Sorry for not providing any documentation before (since I did not expect other people to use it). I just tested it again on my archlinux and added some documentation. Hope it will be straight-forward for you to setup it correctly.
